FROM python:3.9

EXPOSE 8080
ENV AMQP_USER=roboshop \
    AMQP_PASSWORD=roboshop123

USER root

ENV INSTANCE_SERVICE_NAME=payment

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY *.py /app/
COPY payment.ini /app/

#CMD ["paython", "payment.py"]
CMD [ "uwsgi", "--ini", "payment.ini" ]