apiVersion: v1
kind: configMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql

---
apiVersion: v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: 
    app: shipping
    project: roboshop
    tier: app
spec:
  riplicas: 1
  selector:
    matchLabels:
      app: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
        - name: shipping
          image: darauday0/shipping:v1
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: shipping

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    app: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
  