# Deployment for MongoDB database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:             # these labels are deployment labels
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:      # these labels are used to find the pods
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:         # these labels are pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: darauday0/mongodb:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 27017    # Exposes the container's MongoDB port internally

--- 
# ClusterIP Service for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  type: ClusterIP       # Internal-only Service for Pod-to-Pod communication
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017          # Service port, used by other Pods to communicate with MongoDB
      targetPort: 27017    # Maps to the MongoDB container port

